# Generated by Django 3.2.9 on 2021-11-13 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'ordering': ['session_id', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=50)),
                ('element', models.CharField(max_length=50)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='theeyeservice.event')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('payload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='theeyeservice.payload')),
            ],
        ),
    ]
