# Generated by Django 3.2.9 on 2021-11-13 17:04

from django.db import migrations, models
import django.db.models.deletion
import theeyeservice.validators


class Migration(migrations.Migration):

    dependencies = [
        ('theeyeservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(validators=[theeyeservice.validators.validate_event_date_not_future]),
        ),
        migrations.AlterField(
            model_name='payload',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='theeyeservice.event'),
        ),
    ]
