# Generated by Django 3.2.9 on 2021-11-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theeyeservice', '0003_alter_payload_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
