# Generated by Django 3.2.9 on 2021-11-14 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theeyeservice', '0005_auto_20211114_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['session_id', 'timestamp']},
        ),
    ]
