# Generated by Django 3.2.9 on 2021-11-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theeyeservice', '0006_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='session_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='first_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='form',
            name='last_name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='payload',
            name='element',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='payload',
            name='host',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='payload',
            name='path',
            field=models.TextField(),
        ),
    ]
